In [ ]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])

print(a + b)

a + 5      # adds 5 to every element
a * 2      # multiplies every element by 2



[[11 22 33]
 [14 25 36]]


array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
data = np.array([10, 25, 30, 12, 50, 9])
mask = data > 20
print(mask)          # [False  True  True False  True False]
print(data[mask])    # [25 30 50]

print(data[(data > 10) & (data < 30)])   # values between 10 and 30

data[data < 20] = 0
print(data)


[False  True  True False  True False]
[25 30 50]
[25 12]
[ 0 25 30  0 50  0]


In [15]:
np.random.seed(42)        # makes results reproducible (because of seeding)
rand_nums = np.random.randint(1, 7, 10)
print(rand_nums)

print("Mean:", np.mean(rand_nums))
print("Median:", np.median(rand_nums))
print("Std:", np.std(rand_nums))



[4 5 3 5 5 2 3 3 3 5]
Mean: 3.8
Median: 3.5
Std: 1.077032961426901
